// lib/destinations.js
export const DESTINATIONS = [
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    emoji: "🗼",
    gradient: "from-red-100 to-yellow-100",
    badge: "Asia",
    tags: ["Culture", "Food", "Tech", "Nightlife"],
    description: "A city where ancient shrines sit beside neon-lit arcades. Eat your way through Shibuya, wander Yanaka's old alleyways, and watch the city light up from Roppongi Hills.",
    bestTime: "March–May, Oct–Nov",
    avgCost: "$150/day",
    coordinates: { x: 0.82, y: 0.38 },
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    emoji: "🏛️",
    gradient: "from-indigo-100 to-purple-100",
    badge: "Europe",
    tags: ["Romantic", "Beaches", "Views", "Wine"],
    description: "Caldera views, whitewashed villages tumbling toward cobalt seas, and sunsets that rewrite your expectations of beauty.",
    bestTime: "Apr–Jun, Sep–Oct",
    avgCost: "$200/day",
    coordinates: { x: 0.55, y: 0.42 },
  },
  {
    id: "patagonia",
    name: "Patagonia",
    country: "Argentina / Chile",
    emoji: "🏔️",
    gradient: "from-emerald-100 to-teal-100",
    badge: "S. America",
    tags: ["Hiking", "Wildlife", "Glaciers", "Raw"],
    description: "The end of the world on foot. Torres del Paine, Perito Moreno, and skies so big you forget cities exist.",
    bestTime: "Nov–Mar",
    avgCost: "$120/day",
    coordinates: { x: 0.28, y: 0.80 },
  },
  {
    id: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    emoji: "🕌",
    gradient: "from-amber-100 to-orange-100",
    badge: "Africa",
    tags: ["Souks", "Spices", "Art", "Desert"],
    description: "Sensory overload in the best sense. Lose yourself in the medina, find yourself in a riad's courtyard, taste chermoula forever.",
    bestTime: "Mar–May, Sep–Nov",
    avgCost: "$80/day",
    coordinates: { x: 0.44, y: 0.46 },
  },
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    emoji: "⛩️",
    gradient: "from-pink-100 to-orange-100",
    badge: "Asia",
    tags: ["Temples", "Tea", "Geisha", "Zen"],
    description: "Japan's soul made visible. Bamboo groves, a thousand torii, matcha everything, and ryokan mornings that slow time.",
    bestTime: "Mar–May (Cherry Blossom)",
    avgCost: "$130/day",
    coordinates: { x: 0.80, y: 0.40 },
  },
  {
    id: "reykjavik",
    name: "Reykjavík",
    country: "Iceland",
    emoji: "🌋",
    gradient: "from-sky-100 to-cyan-100",
    badge: "Europe",
    tags: ["Aurora", "Hot Springs", "Midnight Sun", "Lava"],
    description: "A tiny capital with outsized magic. Chase the northern lights, soak in geothermal pools, and hike to waterfalls frozen mid-flow.",
    bestTime: "Jun–Aug or Sep–Mar",
    avgCost: "$250/day",
    coordinates: { x: 0.40, y: 0.22 },
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    emoji: "🌺",
    gradient: "from-green-100 to-lime-100",
    badge: "Asia",
    tags: ["Temples", "Surf", "Yoga", "Rice Terraces"],
    description: "Sacred and hedonistic at once. Sunrise on Agung, offerings on every corner, waves at Uluwatu, and the gentlest smiles on earth.",
    bestTime: "Apr–Oct",
    avgCost: "$70/day",
    coordinates: { x: 0.77, y: 0.60 },
  },
  {
    id: "new-york",
    name: "New York",
    country: "USA",
    emoji: "🗽",
    gradient: "from-slate-100 to-blue-100",
    badge: "N. America",
    tags: ["Culture", "Food", "Art", "Energy"],
    description: "The city that made the word metropolitan. Every borough a universe. Every corner a scene. The pizza alone is worth the trip.",
    bestTime: "Apr–Jun, Sep–Nov",
    avgCost: "$280/day",
    coordinates: { x: 0.22, y: 0.36 },
  },
];

export const CATEGORY_EMOJIS = {
  flights:    "✈️",
  hotels:     "🏨",
  food:       "🍜",
  activities: "🎭",
  transport:  "🚆",
  misc:       "◇",
};

